### ISSUE TITLE
Focused window not printing to status bar

### ISSUE THREAD

**Issue by zachary123212** [herrbischoff/nerdbar.widget#2]
It might be important to note that kwmc is installed to the root bin directory, as opposed to the local one. (I have changed the directory from with kwmc is executed in focused-window.coffee). However, nothing is printing to the location in the bar where the focused window is supposed to be named. I have tried running kwmc read focused from the shell, but it has printed nothing.

**Comment by herrbischoff** [comment]
From what I can gather, this appears to be a problem with your `kwm` setup instead of with this widget. If the command does not output anything on the shell, it most probably is not correctly installed. How did you install `kwm`?

FWIW, to my knowledge `kwm` does not install itself anywhere. After compilation you need to copy it manually. The proper place for that is `/usr/local/bin`. You should never install anything in `/bin` or even `/usr/bin`, those are for system tools.

**Comment by zachary123212** [comment]
Yeah, I reinstalled kwm to `/usr/local` but  `kwmc read focused`. However, I can still run `kwmc`, unlike when `kwm` is closed, the command just doesn't return anything.

**Comment by herrbischoff** [comment]
I'd love to be able to help you but this is outside of the scope of this widget. Maybe @koekeishiya can assist in possible causes for this.

**Comment by koekeishiya** [comment]
Uh, I have no idea.

What happens if you run: telnet 127.0.0.1 3020
and type: `read focused `  (notice the trailing space).

**Comment by herrbischoff** [comment]
Closing this because this issue hasn't been updated in more than 14 days.
